In [2]:
!pip install tensorflow
!pip install tensorflow-datasets tensorboard h5py pandas numpy matplotlib scikit-learn

Requirement already satisfied: tensorflow in c:\users\admin\anaconda3\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (2.5.1)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (26.3)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (7.36.2)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (1.85.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (2.3.5)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\admin\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\admin\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Requirement already satisfied: namex in c:\users\admin\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\admin\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\admin\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\admin\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\admin\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Admin\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\Admin\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Admin\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\Admin\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Admin\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\Admin\anaconda3\Lib\site-packages)

Collecting tensorflow-datasets
  Downloading tensorflow_datasets-4.9.10-py3-none-any.whl.metadata (11 kB)
Collecting tensorboard
  Downloading tensorboard-2.21.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: h5py in c:\users\admin\anaconda3\lib\site-packages (3.14.0)
Requirement already satisfied: pandas in c:\users\admin\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\admin\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: matplotlib in c:\users\admin\anaconda3\lib\site-packages (3.10.0)
Requirement already satisfied: scikit-learn in c:\users\admin\anaconda3\lib\site-packages (1.9.0)
Requirement already satisfied: absl-py in c:\users\admin\anaconda3\lib\site-packages (from tensorflow-datasets) (2.5.1)
Collecting dm-tree (from tensorflow-datasets)
  Downloading dm_tree-0.1.10-cp313-cp313-win_amd64.whl.metadata (2.6 kB)
Collecting etils>=1.9.1 (from etils[edc,enp,epath,epy,etree]>=1.9.1; python_version >= "3.11"->tensorflow-datasets)
  Downloading etils-1.14.0-py3-none-any.whl.metadata (6.5 kB)
Collecting immutabledict (from tensorflow-datasets)
  Downloading immutabledict-4.3.1-py3-none-any.whl.metadata (3.5 kB)
Collecting promise (from tensorflow-datasets)
  Downloading promise-2.3.tar.gz (19 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: protobuf>=3.20 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow-datasets) (7.36.2)
Requirement already satisfied: psutil in c:\users\admin\anaconda3\lib\site-packages (from tensorflow-datasets) (7.0.0)
Requirement already satisfied: pyarrow in c:\users\admin\anaconda3\lib\site-packages (from tensorflow-datasets) (21.0.0)
Requirement already satisfied: requests>=2.19.0 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow-datasets) (2.32.5)
Collecting simple_parsing (from tensorflow-datasets)
  Downloading simple_parsing-0.1.9-py3-none-any.whl.metadata (8.1 kB)
Collecting tensorflow-metadata (from tensorflow-datasets)
  Downloading tensorflow_metadata-1.21.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: termcolor in c:\users\admin\anaconda3\lib\site-packages (from tensorflow-datasets) (3.3.0)
Requirement already satisfied: toml in c:\users\admin\anaconda3\lib\site-packages (from tensorflow-datasets) (0.10.2)
Requirement already satisfied: tqdm in c:\users\admin\anaconda3\lib\site-packages (from tensorflow-datasets) (4.67.1)
Requirement already satisfied: wrapt in c:\users\admin\anaconda3\lib\site-packages (from tensorflow-datasets) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in c:\users\admin\anaconda3\lib\site-packages (from tensorboard) (1.85.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\admin\anaconda3\lib\site-packages (from tensorboard) (3.8)
Requirement already satisfied: packaging in c:\users\admin\anaconda3\lib\site-packages (from tensorboard) (26.3)
Requirement already satisfied: pillow in c:\users\admin\anaconda3\lib\site-packages (from tensorboard) (12.0.0)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\admin\anaconda3\lib\site-packages (from tensorboard) (80.9.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard)
  Downloading tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\admin\anaconda3\lib\site-packages (from tensorboard) (3.1.3)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\admin\anaconda3\lib\site-packages (from grpcio<2.0,>=1.74.0->tensorboard) (4.15.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\admin\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.4.0 in c:\users\admin\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\admin\anaconda3\lib\site-packages (from scikit-learn) (2.7.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\admin\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Collecting einops (from etils[edc,enp,epath,epy,etree]>=1.9.1; python_version >= "3.11"->tensorflow-datasets)
  Downloading einops-0.8.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: fsspec in c:\users\admin\anaconda3\lib\site-packages (from etils[edc,enp,epath,epy,etree]>=1.9.1; python_version >= "3.11"->tensorflow-datasets) (2025.10.0)
Requirement already satisfied: zipp in c:\users\admin\anaconda3\lib\site-packages (from etils[edc,enp,epath,epy,etree]>=1.9.1; python_version >= "3.11"->tensorflow-datasets) (3.23.0)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\anaconda3\lib\site-packages (from requests>=2.19.0->tensorflow-datasets) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests>=2.19.0->tensorflow-datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\anaconda3\lib\site-packages (from requests>=2.19.0->tensorflow-datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3\lib\site-packages (from requests>=2.19.0->tensorflow-datasets) (2026.7.22)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\admin\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.2)
Requirement already satisfied: attrs>=18.2.0 in c:\users\admin\anaconda3\lib\site-packages (from dm-tree->tensorflow-datasets) (25.4.0)
Collecting docstring-parser~=0.15 (from simple_parsing->tensorflow-datasets)
  Downloading docstring_parser-0.18.0-py3-none-any.whl.metadata (3.5 kB)
Collecting googleapis-common-protos<2,>=1.56.4 (from tensorflow-metadata->tensorflow-datasets)
  Downloading googleapis_common_protos-1.76.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: colorama in c:\users\admin\anaconda3\lib\site-packages (from tqdm->tensorflow-datasets) (0.4.6)
Downloading tensorflow_datasets-4.9.10-py3-none-any.whl (5.3 MB)
   ---------------------------------------- 0.0/5.3 MB ? eta -:--:--
   ------- -------------------------------- 1.0/5.3 MB 4.7 MB/s eta 0:00:01
   ------------- -------------------------- 1.8/5.3 MB 4.5 MB/s eta 0:00:01
   ------------- -------------------------- 1.8/5.3 MB 4.5 MB/s eta 0:00:01
   ------------- -------------------------- 1.8/5.3 MB 4.5 MB/s eta 0:00:01
   ------------- -------------------------- 1.8/5.3 MB 4.5 MB/s eta 0:00:01
   ------------- -------------------------- 1.8/5.3 MB 4.5 MB/s eta 0:00:01
   ------------- -------------------------- 1.8/5.3 MB 4.5 MB/s eta 0:00:01
   ------------- -------------------------- 1.8/5.3 MB 4.5 MB/s eta 0:00:01
   ------------- -------------------------- 1.8/5.3 MB 4.5 MB/s eta 0:00:01
   --------------- ------------------------ 2.1/5.3 MB 924.2 kB/s eta 0:00:04
   ----------------------- ---------------- 3.1/5.3 MB 1.3 MB/s eta 0:00:02
   ----------------------------- ---------- 3.9/5.3 MB 1.5 MB/s eta 0:00:01
   ----------------------------------- ---- 4.7/5.3 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 5.3/5.3 MB 1.8 MB/s  0:00:02
Downloading tensorboard-2.21.0-py3-none-any.whl (5.5 MB)
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   ----- ---------------------------------- 0.8/5.5 MB 4.8 MB/s eta 0:00:01
   ------------- -------------------------- 1.8/5.5 MB 4.9 MB/s eta 0:00:01
   ------------------- -------------------- 2.6/5.5 MB 4.3 MB/s eta 0:00:01
   ------------------------ --------------- 3.4/5.5 MB 4.3 MB/s eta 0:00:01
   ------------------------------ --------- 4.2/5.5 MB 4.2 MB/s eta 0:00:01
   ------------------------------------ --- 5.0/5.5 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 5.5/5.5 MB 4.1 MB/s  0:00:01
Downloading tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)
Downloading etils-1.14.0-py3-none-any.whl (172 kB)
Downloading dm_tree-0.1.10-cp313-cp313-win_amd64.whl (112 kB)
Downloading einops-0.8.2-py3-none-any.whl (65 kB)
Downloading immutabledict-4.3.1-py3-none-any.whl (5.0 kB)
Downloading simple_parsing-0.1.9-py3-none-any.whl (113 kB)
Downloading docstring_parser-0.18.0-py3-none-any.whl (22 kB)
Downloading tensorflow_metadata-1.21.0-py3-none-any.whl (30 kB)
Downloading googleapis_common_protos-1.76.0-py3-none-any.whl (307 kB)
Building wheels for collected packages: promise
  Building wheel for promise (pyproject.toml): started
  Building wheel for promise (pyproject.toml): finished with status 'done'
  Created wheel for promise: filename=promise-2.3-py3-none-any.whl size=21644 sha256=8aa610b3db72eeb89c94e0e2fb8560f095d25a65dded8523bab56ea13f27ca01
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\8f\46\1c\1f4e5d73a20eb816ead5014e97cdeb3928cf314fc46c7bab61
Successfully built promise
Installing collected packages: tensorboard-data-server, promise, immutabledict, googleapis-common-protos, etils, einops, docstring-parser, dm-tree, tensorflow-metadata, tensorboard, simple_parsing, tensorflow-datasets

   ---------- -----------------------------  3/12 [googleapis-common-protos]
   ---------- -----------------------------  3/12 [googleapis-common-protos]
   ---------- -----------------------------  3/12 [googleapis-common-protos]
   ---------- -----------------------------  3/12 [googleapis-common-protos]
   ------------- --------------------------  4/12 [etils]
   ------------- --------------------------  4/12 [etils]
   ------------- --------------------------  4/12 [etils]
   ------------- --------------------------  4/12 [etils]
   ------------- --------------------------  4/12 [etils]
   ---------------- -----------------------  5/12 [einops]
   ---------------- -----------------------  5/12 [einops]
   ---------------- -----------------------  5/12 [einops]
   -------------------- -------------------  6/12 [docstring-parser]
   -------------------------- -------------  8/12 [tensorflow-metadata]
   ------------------------------ ---------  9/12 [tensorboard]
   ------------------------------ ---------  9/12 [tensorboard]
   ------------------------------ ---------  9/12 [tensorboard]
   ------------------------------ ---------  9/12 [tensorboard]
   ------------------------------ ---------  9/12 [tensorboard]
   ------------------------------ ---------  9/12 [tensorboard]
   ------------------------------ ---------  9/12 [tensorboard]
   ------------------------------ ---------  9/12 [tensorboard]
   ------------------------------ ---------  9/12 [tensorboard]
   ------------------------------ ---------  9/12 [tensorboard]
   ------------------------------ ---------  9/12 [tensorboard]
   ------------------------------ ---------  9/12 [tensorboard]
   ------------------------------ ---------  9/12 [tensorboard]
   ------------------------------ ---------  9/12 [tensorboard]
   ------------------------------ ---------  9/12 [tensorboard]
   --------------------------------- ------ 10/12 [simple_parsing]
   --------------------------------- ------ 10/12 [simple_parsing]
   --------------------------------- ------ 10/12 [simple_parsing]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ------------------------------------ --- 11/12 [tensorflow-datasets]
   ---------------------------------------- 12/12 [tensorflow-datasets]

Successfully installed dm-tree-0.1.10 docstring-parser-0.18.0 einops-0.8.2 etils-1.14.0 googleapis-common-protos-1.76.0 immutabledict-4.3.1 promise-2.3 simple_parsing-0.1.9 tensorboard-2.21.0 tensorboard-data-server-0.7.2 tensorflow-datasets-4.9.10 tensorflow-metadata-1.21.0

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Admin\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\Admin\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Admin\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\Admin\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Admin\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\Admin\anaconda3\Lib\site-packages)

In [3]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [4]:
!pip install keras-cv keras-nlp

Collecting keras-cv
  Downloading keras_cv-0.9.0-py3-none-any.whl.metadata (12 kB)
Collecting keras-nlp
  Downloading keras_nlp-0.32.0-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: packaging in c:\users\admin\anaconda3\lib\site-packages (from keras-cv) (26.3)
Requirement already satisfied: absl-py in c:\users\admin\anaconda3\lib\site-packages (from keras-cv) (2.5.1)
Requirement already satisfied: regex in c:\users\admin\anaconda3\lib\site-packages (from keras-cv) (2025.9.1)
Requirement already satisfied: tensorflow-datasets in c:\users\admin\anaconda3\lib\site-packages (from keras-cv) (4.9.10)
Collecting keras-core (from keras-cv)
  Downloading keras_core-0.1.7-py3-none-any.whl.metadata (4.3 kB)
Collecting kagglehub (from keras-cv)
  Downloading kagglehub-1.0.3-py3-none-any.whl.metadata (40 kB)
Collecting keras-hub==0.32.0 (from keras-nlp)
  Downloading keras_hub-0.32.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: keras>=3.15 in c:\users\admin\anaconda3\lib\site-packages (from keras-hub==0.32.0->keras-nlp) (3.15.1)
Requirement already satisfied: numpy in c:\users\admin\anaconda3\lib\site-packages (from keras-hub==0.32.0->keras-nlp) (2.3.5)
Requirement already satisfied: rich in c:\users\admin\anaconda3\lib\site-packages (from keras-hub==0.32.0->keras-nlp) (14.2.0)
Collecting kagglesdk==0.1.28 (from keras-hub==0.32.0->keras-nlp)
  Downloading kagglesdk-0.1.28-py3-none-any.whl.metadata (13 kB)
Collecting sentencepiece (from keras-hub==0.32.0->keras-nlp)
  Downloading sentencepiece-0.2.2-cp313-cp313-win_amd64.whl.metadata (34 kB)
Collecting tokenizers (from keras-hub==0.32.0->keras-nlp)
  Downloading tokenizers-0.23.3-cp310-abi3-win_amd64.whl.metadata (10 kB)
Requirement already satisfied: protobuf in c:\users\admin\anaconda3\lib\site-packages (from kagglesdk==0.1.28->keras-hub==0.32.0->keras-nlp) (7.36.2)
Requirement already satisfied: requests in c:\users\admin\anaconda3\lib\site-packages (from kagglesdk==0.1.28->keras-hub==0.32.0->keras-nlp) (2.32.5)
Collecting certifi>=2026.10.19 (from kagglehub->keras-cv)
  Downloading certifi-2026.10.23-py3-none-any.whl.metadata (2.5 kB)
INFO: pip is looking at multiple versions of kagglehub to determine which version is compatible with other requirements. This could take a while.
Collecting kagglehub (from keras-cv)
  Downloading kagglehub-1.0.2-py3-none-any.whl.metadata (40 kB)
Requirement already satisfied: pyyaml in c:\users\admin\anaconda3\lib\site-packages (from kagglehub->keras-cv) (6.0.3)
Requirement already satisfied: tqdm in c:\users\admin\anaconda3\lib\site-packages (from kagglehub->keras-cv) (4.67.1)
Requirement already satisfied: namex in c:\users\admin\anaconda3\lib\site-packages (from keras>=3.15->keras-hub==0.32.0->keras-nlp) (0.1.0)
Requirement already satisfied: h5py in c:\users\admin\anaconda3\lib\site-packages (from keras>=3.15->keras-hub==0.32.0->keras-nlp) (3.14.0)
Requirement already satisfied: optree in c:\users\admin\anaconda3\lib\site-packages (from keras>=3.15->keras-hub==0.32.0->keras-nlp) (0.20.0)
Requirement already satisfied: ml-dtypes in c:\users\admin\anaconda3\lib\site-packages (from keras>=3.15->keras-hub==0.32.0->keras-nlp) (0.6.0)
Requirement already satisfied: dm-tree in c:\users\admin\anaconda3\lib\site-packages (from keras-core->keras-cv) (0.1.10)
Requirement already satisfied: attrs>=18.2.0 in c:\users\admin\anaconda3\lib\site-packages (from dm-tree->keras-core->keras-cv) (25.4.0)
Requirement already satisfied: wrapt>=1.11.2 in c:\users\admin\anaconda3\lib\site-packages (from dm-tree->keras-core->keras-cv) (1.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\admin\anaconda3\lib\site-packages (from optree->keras>=3.15->keras-hub==0.32.0->keras-nlp) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\anaconda3\lib\site-packages (from requests->kagglesdk==0.1.28->keras-hub==0.32.0->keras-nlp) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests->kagglesdk==0.1.28->keras-hub==0.32.0->keras-nlp) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\anaconda3\lib\site-packages (from requests->kagglesdk==0.1.28->keras-hub==0.32.0->keras-nlp) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3\lib\site-packages (from requests->kagglesdk==0.1.28->keras-hub==0.32.0->keras-nlp) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\admin\anaconda3\lib\site-packages (from rich->keras-hub==0.32.0->keras-nlp) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\admin\anaconda3\lib\site-packages (from rich->keras-hub==0.32.0->keras-nlp) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\admin\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras-hub==0.32.0->keras-nlp) (0.1.2)
Requirement already satisfied: etils>=1.9.1 in c:\users\admin\anaconda3\lib\site-packages (from etils[edc,enp,epath,epy,etree]>=1.9.1; python_version >= "3.11"->tensorflow-datasets->keras-cv) (1.14.0)
Requirement already satisfied: immutabledict in c:\users\admin\anaconda3\lib\site-packages (from tensorflow-datasets->keras-cv) (4.3.1)
Requirement already satisfied: promise in c:\users\admin\anaconda3\lib\site-packages (from tensorflow-datasets->keras-cv) (2.3)
Requirement already satisfied: psutil in c:\users\admin\anaconda3\lib\site-packages (from tensorflow-datasets->keras-cv) (7.0.0)
Requirement already satisfied: pyarrow in c:\users\admin\anaconda3\lib\site-packages (from tensorflow-datasets->keras-cv) (21.0.0)
Requirement already satisfied: simple_parsing in c:\users\admin\anaconda3\lib\site-packages (from tensorflow-datasets->keras-cv) (0.1.9)
Requirement already satisfied: tensorflow-metadata in c:\users\admin\anaconda3\lib\site-packages (from tensorflow-datasets->keras-cv) (1.21.0)
Requirement already satisfied: termcolor in c:\users\admin\anaconda3\lib\site-packages (from tensorflow-datasets->keras-cv) (3.3.0)
Requirement already satisfied: toml in c:\users\admin\anaconda3\lib\site-packages (from tensorflow-datasets->keras-cv) (0.10.2)
Requirement already satisfied: einops in c:\users\admin\anaconda3\lib\site-packages (from etils[edc,enp,epath,epy,etree]>=1.9.1; python_version >= "3.11"->tensorflow-datasets->keras-cv) (0.8.2)
Requirement already satisfied: fsspec in c:\users\admin\anaconda3\lib\site-packages (from etils[edc,enp,epath,epy,etree]>=1.9.1; python_version >= "3.11"->tensorflow-datasets->keras-cv) (2025.10.0)
Requirement already satisfied: zipp in c:\users\admin\anaconda3\lib\site-packages (from etils[edc,enp,epath,epy,etree]>=1.9.1; python_version >= "3.11"->tensorflow-datasets->keras-cv) (3.23.0)
Requirement already satisfied: six in c:\users\admin\anaconda3\lib\site-packages (from promise->tensorflow-datasets->keras-cv) (1.17.0)
Requirement already satisfied: docstring-parser~=0.15 in c:\users\admin\anaconda3\lib\site-packages (from simple_parsing->tensorflow-datasets->keras-cv) (0.18.0)
Requirement already satisfied: googleapis-common-protos<2,>=1.56.4 in c:\users\admin\anaconda3\lib\site-packages (from tensorflow-metadata->tensorflow-datasets->keras-cv) (1.76.0)
Collecting huggingface-hub<3.0,>=0.16.4 (from tokenizers->keras-hub==0.32.0->keras-nlp)
  Downloading huggingface_hub-2.3.0-py3-none-any.whl.metadata (16 kB)
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub<3.0,>=0.16.4->tokenizers->keras-hub==0.32.0->keras-nlp)
  Using cached click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock>=3.10.0 in c:\users\admin\anaconda3\lib\site-packages (from huggingface-hub<3.0,>=0.16.4->tokenizers->keras-hub==0.32.0->keras-nlp) (3.20.0)
Collecting hf-xet<2.0.0,>=1.6.0 (from huggingface-hub<3.0,>=0.16.4->tokenizers->keras-hub==0.32.0->keras-nlp)
  Downloading hf_xet-1.7.0-cp38-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting httpx2<3,>=2.0.0 (from huggingface-hub<3.0,>=0.16.4->tokenizers->keras-hub==0.32.0->keras-nlp)
  Downloading httpx2-2.16.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: anyio>=4.10 in c:\users\admin\anaconda3\lib\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=0.16.4->tokenizers->keras-hub==0.32.0->keras-nlp) (4.10.0)
Collecting httpcore2==2.16.0 (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=0.16.4->tokenizers->keras-hub==0.32.0->keras-nlp)
  Downloading httpcore2-2.16.0-py3-none-any.whl.metadata (27 kB)
Collecting idna<4,>=2.5 (from requests->kagglesdk==0.1.28->keras-hub==0.32.0->keras-nlp)
  Using cached idna-3.20-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: truststore>=0.10 in c:\users\admin\anaconda3\lib\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=0.16.4->tokenizers->keras-hub==0.32.0->keras-nlp) (0.10.1)
Requirement already satisfied: h11>=0.16 in c:\users\admin\anaconda3\lib\site-packages (from httpcore2==2.16.0->httpx2<3,>=2.0.0->huggingface-hub<3.0,>=0.16.4->tokenizers->keras-hub==0.32.0->keras-nlp) (0.16.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\admin\anaconda3\lib\site-packages (from anyio>=4.10->httpx2<3,>=2.0.0->huggingface-hub<3.0,>=0.16.4->tokenizers->keras-hub==0.32.0->keras-nlp) (1.3.0)
Requirement already satisfied: colorama in c:\users\admin\anaconda3\lib\site-packages (from tqdm->kagglehub->keras-cv) (0.4.6)
Downloading keras_cv-0.9.0-py3-none-any.whl (650 kB)
   ---------------------------------------- 0.0/650.7 kB ? eta -:--:--
   ---------------------------------------- 650.7/650.7 kB 6.4 MB/s  0:00:00
Downloading keras_nlp-0.32.0-py3-none-any.whl (1.8 kB)
Downloading keras_hub-0.32.0-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------------------------ --------------- 1.0/1.7 MB 4.7 MB/s eta 0:00:01
   ------------------------ --------------- 1.0/1.7 MB 4.7 MB/s eta 0:00:01
   ------------------------ --------------- 1.0/1.7 MB 4.7 MB/s eta 0:00:01
   ------------------------ --------------- 1.0/1.7 MB 4.7 MB/s eta 0:00:01
   ------------------------ --------------- 1.0/1.7 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 1.2 MB/s  0:00:01
Downloading kagglesdk-0.1.28-py3-none-any.whl (230 kB)
Downloading kagglehub-1.0.2-py3-none-any.whl (70 kB)
Downloading keras_core-0.1.7-py3-none-any.whl (950 kB)
   ---------------------------------------- 0.0/950.8 kB ? eta -:--:--
   ---------------------------------------- 950.8/950.8 kB 3.7 MB/s  0:00:00
Downloading sentencepiece-0.2.2-cp313-cp313-win_amd64.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------- ----------------------- 0.5/1.2 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 3.4 MB/s  0:00:00
Downloading tokenizers-0.23.3-cp310-abi3-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ---------- ----------------------------- 0.8/2.9 MB 4.4 MB/s eta 0:00:01
   ------------------------- -------------- 1.8/2.9 MB 5.0 MB/s eta 0:00:01
   ------------------------------------ --- 2.6/2.9 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 3.5 MB/s  0:00:00
Downloading huggingface_hub-2.3.0-py3-none-any.whl (855 kB)
   ---------------------------------------- 0.0/855.2 kB ? eta -:--:--
   ------------------------------------ --- 786.4/855.2 kB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 855.2/855.2 kB 3.9 MB/s  0:00:00
Using cached click-8.5.0-py3-none-any.whl (125 kB)
Downloading hf_xet-1.7.0-cp38-abi3-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------- ----------------------------- 1.0/3.8 MB 5.3 MB/s eta 0:00:01
   ------------------- -------------------- 1.8/3.8 MB 4.9 MB/s eta 0:00:01
   --------------------------- ------------ 2.6/3.8 MB 4.3 MB/s eta 0:00:01
   ----------------------------------- ---- 3.4/3.8 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 4.0 MB/s  0:00:00
Downloading httpx2-2.16.0-py3-none-any.whl (97 kB)
Downloading httpcore2-2.16.0-py3-none-any.whl (85 kB)
Using cached idna-3.20-py3-none-any.whl (69 kB)
Installing collected packages: sentencepiece, idna, httpcore2, hf-xet, click, keras-core, kagglesdk, httpx2, kagglehub, huggingface-hub, tokenizers, keras-hub, keras-cv, keras-nlp

  Attempting uninstall: idna

    Found existing installation: idna 3.11

    Uninstalling idna-3.11:

      Successfully uninstalled idna-3.11

   -- -------------------------------------  1/14 [idna]
   ----- ----------------------------------  2/14 [httpcore2]
   -------- -------------------------------  3/14 [hf-xet]
  Attempting uninstall: click
   -------- -------------------------------  3/14 [hf-xet]
    Found existing installation: click 8.2.1
   -------- -------------------------------  3/14 [hf-xet]
    Uninstalling click-8.2.1:
   -------- -------------------------------  3/14 [hf-xet]
      Successfully uninstalled click-8.2.1
   -------- -------------------------------  3/14 [hf-xet]
   ----------- ----------------------------  4/14 [click]
   ----------- ----------------------------  4/14 [click]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   -------------- -------------------------  5/14 [keras-core]
   ----------------- ----------------------  6/14 [kagglesdk]
   ----------------- ----------------------  6/14 [kagglesdk]
   ----------------- ----------------------  6/14 [kagglesdk]
   ----------------- ----------------------  6/14 [kagglesdk]
   ----------------- ----------------------  6/14 [kagglesdk]
   ----------------- ----------------------  6/14 [kagglesdk]
   ----------------- ----------------------  6/14 [kagglesdk]
   ----------------- ----------------------  6/14 [kagglesdk]
   -------------------- -------------------  7/14 [httpx2]
   -------------------- -------------------  7/14 [httpx2]
   -------------------- -------------------  7/14 [httpx2]
   ---------------------- -----------------  8/14 [kagglehub]
   ---------------------- -----------------  8/14 [kagglehub]
   ------------------------- --------------  9/14 [huggingface-hub]
   ------------------------- --------------  9/14 [huggingface-hub]
   ------------------------- --------------  9/14 [huggingface-hub]
   ------------------------- --------------  9/14 [huggingface-hub]
   ------------------------- --------------  9/14 [huggingface-hub]
   ------------------------- --------------  9/14 [huggingface-hub]
   ------------------------- --------------  9/14 [huggingface-hub]
   ------------------------- --------------  9/14 [huggingface-hub]
   ------------------------- --------------  9/14 [huggingface-hub]
   ------------------------- --------------  9/14 [huggingface-hub]
   ------------------------- --------------  9/14 [huggingface-hub]
   ------------------------- --------------  9/14 [huggingface-hub]
   ---------------------------- ----------- 10/14 [tokenizers]
   ---------------------------- ----------- 10/14 [tokenizers]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ------------------------------- -------- 11/14 [keras-hub]
   ---------------------------------- ----- 12/14 [keras-cv]
   ---------------------------------- ----- 12/14 [keras-cv]
   ---------------------------------- ----- 12/14 [keras-cv]
   ---------------------------------- ----- 12/14 [keras-cv]
   ---------------------------------- ----- 12/14 [keras-cv]
   ---------------------------------- ----- 12/14 [keras-cv]
   ---------------------------------- ----- 12/14 [keras-cv]
   ---------------------------------- ----- 12/14 [keras-cv]
   ---------------------------------- ----- 12/14 [keras-cv]
   ---------------------------------- ----- 12/14 [keras-cv]
   ---------------------------------- ----- 12/14 [keras-cv]
   ---------------------------------- ----- 12/14 [keras-cv]
   ---------------------------------- ----- 12/14 [keras-cv]
   ---------------------------------- ----- 12/14 [keras-cv]
   ---------------------------------- ----- 12/14 [keras-cv]
   ---------------------------------- ----- 12/14 [keras-cv]

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Admin\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\Admin\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Admin\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\Admin\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Admin\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\Admin\anaconda3\Lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.51.0 requires packaging<26,>=20, but you have packaging 26.3 which is incompatible.
streamlit 1.51.0 requires protobuf<7,>=3.20, but you have protobuf 7.36.2 which is incompatible.

In [7]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [11]:
df

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [12]:
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [13]:
model = Sequential()
model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

C:\Users\Admin\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [14]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.get_weights()

[array([[ 0.986827  , -0.04590857],
        [ 0.96366537, -0.27045947]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.17504835],
        [-0.58919305]], dtype=float32),
 array([0.], dtype=float32)]

In [16]:
new_weights = [np.array([[0.1, 0.1],
                        [0.1, 0.1]]),
np.array([0., 0.]),
np.array([[0.1],
          [0.1]]),
np.array([0.])]

In [17]:
model.set_weights(new_weights)

In [18]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [19]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [22]:
model.fit(df.iloc[:,:-1].values, df['lpa'].values, epochs=100, verbose=1, batch_size=1)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.4379
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.3994
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.3626
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3214
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.2788
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.2640
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.2300
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.2171
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.1797
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.1661
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.1409
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.1361
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.1171
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.1028
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.0957
Epoch 16/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.0958
Epoch 17/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.0830
Epoch 18/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.0712
Epoch 19/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0645
Epoch 20/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.0595
Epoch 21/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.0521
Epoch 22/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.0472
Epoch 23/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.0503
Epoch 24/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0395
Epoch 25/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.0365
Epoch 26/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.0422
Epoch 27/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0377
Epoch 28/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0273
Epoch 29/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0234
Epoch 30/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.0212
Epoch 31/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0204
Epoch 32/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0175
Epoch 33/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.0156
Epoch 34/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.0211
Epoch 35/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.0107
Epoch 36/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0080
Epoch 37/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.0068
Epoch 38/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.0118
Epoch 39/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.0041
Epoch 40/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0013
Epoch 41/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.0026
Epoch 42/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.9987
Epoch 43/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.9963
Epoch 44/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.9946
Epoch 45/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.9946
Epoch 46/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.9922
Epoch 47/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.9901
Epoch 48/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.9874
Epoch 49/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.9856
Epoch 50/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.9876
Epoch 51/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9848
Epoch 52/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9840
Epoch 53/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9799
Epoch 54/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9770
Epoch 55/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9751
Epoch 56/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.9735
Epoch 57/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.9728
Epoch 58/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9706
Epoch 59/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9693
Epoch 60/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9678
Epoch 61/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.9651
Epoch 62/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.9632
Epoch 63/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.9648
Epoch 64/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9629
Epoch 65/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.9594
Epoch 66/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.9569
Epoch 67/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.9565
Epoch 68/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9538
Epoch 69/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9545
Epoch 70/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.9543
Epoch 71/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.9507
Epoch 72/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.9497
Epoch 73/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.9456
Epoch 74/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9444
Epoch 75/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.9421
Epoch 76/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.9399
Epoch 77/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.9375
Epoch 78/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.9358
Epoch 79/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.9346
Epoch 80/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.9348
Epoch 81/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.9325
Epoch 82/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.9334
Epoch 83/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.9274
Epoch 84/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.9265
Epoch 85/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9250
Epoch 86/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9227
Epoch 87/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.9222
Epoch 88/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9198
Epoch 89/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.9188
Epoch 90/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9156
Epoch 91/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9146
Epoch 92/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.9127
Epoch 93/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.9109
Epoch 94/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.9129
Epoch 95/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.9081
Epoch 96/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.9077
Epoch 97/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.9081
Epoch 98/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.9054
Epoch 99/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.9016
Epoch 100/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.9011

In [23]:
model.get_weights()

[array([[0.34814426, 0.34814426],
        [0.41956908, 0.41956908]], dtype=float32),
 array([0.2932623, 0.2932623], dtype=float32),
 array([[0.39982712],
        [0.39982712]], dtype=float32),
 array([0.21673754], dtype=float32)]

In [24]:
## Binary Cross Entropy 

df1 = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [25]:
df1

   cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [26]:
def initialize_parameters(layer_dims):
    
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)
    
    for l in range(1, L):
        parameters['W' + str(l)] = np.ones((layer_dims[l], layer_dims[l-1])) * 0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
        
    return parameters

In [27]:
# Utility Functions
def sigmoid(Z):
    
    A = 1 / (1 + np.exp(-Z))
    
    return A

In [51]:
def linear_forward(A_prev, W, b):
    Z = np.dot(W, A_prev) + b
    A = sigmoid(Z)
    
    return A

In [52]:
def L_layer_forward(X, parameters):
    
    A = X
    L = len(parameters) // 2  # number of layers in the neural network
    
    for l in range(1, L+1):
        A_prev = A
        W1 = parameters['W' + str(l)]
        b1 = parameters['b' + str(l)]
        
        A = linear_forward(A_prev, W1, b1)
        
    return A, A_prev

In [55]:
def update_parameters(parameters,y,y_hat,A1,X):
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
    # parameters['W2'][1][0] removed because W2 only has 1 row
    parameters['b2'][0][0] = parameters['b2'][0][0] + (0.0001 * (y - y_hat))
    
    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))
    
    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[1][0]*(1-A1[1][0]))

In [56]:
X = df1[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape (no of features, no. of training example)
y = df1[['placed']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat, A1 = L_layer_forward(X, parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ', -y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.613402628898913

{'W1': array([[0.10000513, 0.10000513],
        [0.10000513, 0.10000513]]),
 'b1': array([[6.41054186e-07],
        [6.41054186e-07]]),
 'W2': array([[0.10003815, 0.1       ]]),
 'b2': array([[4.5849481e-05]])}

In [63]:
X = df1[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training example)
y = df1[['placed']].values[1][0]

y_hat, A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.6134226250548591

{'W1': array([[0.10000561, 0.09999909],
        [0.10000561, 0.09999909]]),
 'b1': array([[2.93941353e-07],
        [2.93941353e-07]]),
 'W2': array([[0.10001743, 0.1       ]]),
 'b2': array([[2.09479953e-05]])}

In [62]:
X = df1[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training example)
y = df1[['placed']].values[2][0]

y_hat, A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.7798337640674536

{'W1': array([[0.10000112, 0.09999332],
        [0.10000112, 0.09999332]]),
 'b1': array([[-3.47017562e-07],
        [-3.47017562e-07]]),
 'W2': array([[0.09997928, 0.1       ]]),
 'b2': array([[-2.49025685e-05]])}

In [65]:
X = df1[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = df1[['placed']].values[3][0]

y_hat, A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.7689414705313449

{'W1': array([[0.10000034, 0.09999382],
        [0.10000034, 0.09999382]]),
 'b1': array([[-7.60633411e-07],
        [-7.60633411e-07]]),
 'W2': array([[0.09997821, 0.1       ]]),
 'b2': array([[-3.27016606e-05]])}

In [66]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 50

for i in range(epochs):
    
    Loss = []
    
    for j in range(df1.shape[0]):
        
        X = df1[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
        y = df1[['placed']].values[j][0]
        
        # Parameter initialization
        
        y_hat, A1 = L_layer_forward(X,parameters)
        y_hat = y_hat[0][0]
        
        update_parameters(parameters,y,y_hat,A1,X)
        
        Loss.append(-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))
        
    print('Epoch - ', i+1, 'Loss - ', np.array(Loss).mean())

parameters

Epoch -  1 Loss -  0.6939044224288834
Epoch -  2 Loss -  0.693903594269023
Epoch -  3 Loss -  0.6939027663776398
Epoch -  4 Loss -  0.6939019387546399
Epoch -  5 Loss -  0.6939011113999298
Epoch -  6 Loss -  0.6939002843134152
Epoch -  7 Loss -  0.6938994574950024
Epoch -  8 Loss -  0.6938986309445977
Epoch -  9 Loss -  0.6938978046621074
Epoch -  10 Loss -  0.6938969786474376
Epoch -  11 Loss -  0.6938961529004947
Epoch -  12 Loss -  0.693895327421185
Epoch -  13 Loss -  0.6938945022094147
Epoch -  14 Loss -  0.6938936772650907
Epoch -  15 Loss -  0.693892852588119
Epoch -  16 Loss -  0.6938920281784062
Epoch -  17 Loss -  0.6938912040358589
Epoch -  18 Loss -  0.6938903801603837
Epoch -  19 Loss -  0.6938895565518869
Epoch -  20 Loss -  0.6938887332102754
Epoch -  21 Loss -  0.6938879101354558
Epoch -  22 Loss -  0.6938870873273346
Epoch -  23 Loss -  0.6938862647858187
Epoch -  24 Loss -  0.6938854425108147
Epoch -  25 Loss -  0.6938846205022298
Epoch -  26 Loss -  0.6938837987599702
Epoch -  27 Loss -  0.693882977283943
Epoch -  28 Loss -  0.6938821560740552
Epoch -  29 Loss -  0.6938813351302138
Epoch -  30 Loss -  0.6938805144523255
Epoch -  31 Loss -  0.6938796940402975
Epoch -  32 Loss -  0.6938788738940365
Epoch -  33 Loss -  0.6938780540134498
Epoch -  34 Loss -  0.6938772343984445
Epoch -  35 Loss -  0.6938764150489278
Epoch -  36 Loss -  0.6938755959648066
Epoch -  37 Loss -  0.6938747771459884
Epoch -  38 Loss -  0.6938739585923799
Epoch -  39 Loss -  0.6938731403038891
Epoch -  40 Loss -  0.6938723222804227
Epoch -  41 Loss -  0.6938715045218883
Epoch -  42 Loss -  0.6938706870281931
Epoch -  43 Loss -  0.6938698697992446
Epoch -  44 Loss -  0.6938690528349502
Epoch -  45 Loss -  0.6938682361352173
Epoch -  46 Loss -  0.6938674196999534
Epoch -  47 Loss -  0.6938666035290663
Epoch -  48 Loss -  0.6938657876224631
Epoch -  49 Loss -  0.6938649719800518
Epoch -  50 Loss -  0.6938641566017397

{'W1': array([[0.09999039, 0.0999033 ],
        [0.09999039, 0.0999033 ]]),
 'b1': array([[-2.63793867e-05],
        [-2.63793867e-05]]),
 'W2': array([[0.09960298, 0.1       ]]),
 'b2': array([[-0.00080259]])}

In [70]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

In [71]:
#now using Keras for binary classification
df2 = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [74]:
model = Sequential()
model.add(Dense(2, activation='sigmoid', input_dim=2))
model.add(Dense(1, activation='sigmoid'))

C:\Users\Admin\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [75]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [76]:
model.get_weights()

[array([[ 0.6934103 , -0.7754383 ],
        [-0.2743922 ,  0.72477305]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.18367624],
        [-0.09644485]], dtype=float32),
 array([0.], dtype=float32)]

In [79]:
new_weights = [np.array([[0.1, 0.1],
                         [0.1, 0.1]], dtype=np.float32),
               np.array([0., 0.], dtype=np.float32),
               np.array([[0.1],
                         [0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [80]:
model.set_weights(new_weights)

In [82]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [84]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy', optimizer=optimizer)

model.fit(df.iloc[:,0:-1].values, df2['placed'].values, epochs=50, verbose=1, batch_size=1)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.6981
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6968
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6967
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6966
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6966
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6965
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6965
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6964
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6964
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6962
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6963
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6961
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6962
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6962
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6960
Epoch 16/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6960
Epoch 17/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6960
Epoch 18/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6959
Epoch 19/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6959
Epoch 20/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6958
Epoch 21/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6957
Epoch 22/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6956
Epoch 23/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6959
Epoch 24/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.6955
Epoch 25/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6955
Epoch 26/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6957
Epoch 27/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6954
Epoch 28/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6954
Epoch 29/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6953
Epoch 30/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6952
Epoch 31/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6952
Epoch 32/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6953
Epoch 33/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6952
Epoch 34/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6951
Epoch 35/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6950
Epoch 36/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6951
Epoch 37/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6950
Epoch 38/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6950
Epoch 39/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6949
Epoch 40/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6948
Epoch 41/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6948
Epoch 42/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6948
Epoch 43/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6950
Epoch 44/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6947
Epoch 45/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6946
Epoch 46/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6948
Epoch 47/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6945
Epoch 48/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6947
Epoch 49/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6944
Epoch 50/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6944

In [85]:
import IPython

# 1. Automatically save the current notebook checkpoint
IPython.get_ipython().run_cell_magic('javascript', '', 'IPython.notebook.save_checkpoint();')

# 2. Add, commit, and push automatically to whichever repo you are in
!git add .
!git commit -m "Auto-update notebooks"
!git push origin main

warning: in the working copy of 'backpropagation_regression_maths.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/placement-checkpoint.csv', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'backpropagation by keras.ipynb', LF will be replaced by CRLF the next time Git touches it

[main 0a567f6] Auto-update notebooks
 5 files changed, 2102 insertions(+), 39 deletions(-)
 rename .ipynb_checkpoints/{Untitled-checkpoint.ipynb => backpropagation by keras-checkpoint.ipynb} (100%)
 create mode 100644 .ipynb_checkpoints/placement-checkpoint.csv
 delete mode 100644 Untitled.ipynb
 create mode 100644 backpropagation by keras.ipynb

To https://github.com/devanshnigam2004-bit/Practice_DL.git
   0f6937f..0a567f6  main -> main